/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MaterialslistRouteImport } from './routes/materialslist'
import { Route as ExamslistRouteImport } from './routes/examslist'
import { Route as EpqsRouteImport } from './routes/epqs'
import { Route as EpceRouteImport } from './routes/epce'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as CourseRouteImport } from './routes/course'

const MaterialslistRoute = MaterialslistRouteImport.update({
  id: '/materialslist',
  path: '/materialslist',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamslistRoute = ExamslistRouteImport.update({
  id: '/examslist',
  path: '/examslist',
  getParentRoute: () => rootRouteImport,
} as any)
const EpqsRoute = EpqsRouteImport.update({
  id: '/epqs',
  path: '/epqs',
  getParentRoute: () => rootRouteImport,
} as any)
const EpceRoute = EpceRouteImport.update({
  id: '/epce',
  path: '/epce',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const CourseRoute = CourseRouteImport.update({
  id: '/course',
  path: '/course',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/course': typeof CourseRoute
  '/courses': typeof CoursesRoute
  '/epce': typeof EpceRoute
  '/epqs': typeof EpqsRoute
  '/examslist': typeof ExamslistRoute
  '/materialslist': typeof MaterialslistRoute
}
export interface FileRoutesByTo {
  '/course': typeof CourseRoute
  '/courses': typeof CoursesRoute
  '/epce': typeof EpceRoute
  '/epqs': typeof EpqsRoute
  '/examslist': typeof ExamslistRoute
  '/materialslist': typeof MaterialslistRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/course': typeof CourseRoute
  '/courses': typeof CoursesRoute
  '/epce': typeof EpceRoute
  '/epqs': typeof EpqsRoute
  '/examslist': typeof ExamslistRoute
  '/materialslist': typeof MaterialslistRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/course'
    | '/courses'
    | '/epce'
    | '/epqs'
    | '/examslist'
    | '/materialslist'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/course'
    | '/courses'
    | '/epce'
    | '/epqs'
    | '/examslist'
    | '/materialslist'
  id:
    | '__root__'
    | '/course'
    | '/courses'
    | '/epce'
    | '/epqs'
    | '/examslist'
    | '/materialslist'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  CourseRoute: typeof CourseRoute
  CoursesRoute: typeof CoursesRoute
  EpceRoute: typeof EpceRoute
  EpqsRoute: typeof EpqsRoute
  ExamslistRoute: typeof ExamslistRoute
  MaterialslistRoute: typeof MaterialslistRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/materialslist': {
      id: '/materialslist'
      path: '/materialslist'
      fullPath: '/materialslist'
      preLoaderRoute: typeof MaterialslistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examslist': {
      id: '/examslist'
      path: '/examslist'
      fullPath: '/examslist'
      preLoaderRoute: typeof ExamslistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/epqs': {
      id: '/epqs'
      path: '/epqs'
      fullPath: '/epqs'
      preLoaderRoute: typeof EpqsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/epce': {
      id: '/epce'
      path: '/epce'
      fullPath: '/epce'
      preLoaderRoute: typeof EpceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/course': {
      id: '/course'
      path: '/course'
      fullPath: '/course'
      preLoaderRoute: typeof CourseRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  CourseRoute: CourseRoute,
  CoursesRoute: CoursesRoute,
  EpceRoute: EpceRoute,
  EpqsRoute: EpqsRoute,
  ExamslistRoute: ExamslistRoute,
  MaterialslistRoute: MaterialslistRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
