/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CoursesIndexRouteImport } from './routes/courses/index'
import { Route as CoursesCourseIdIndexRouteImport } from './routes/courses/$courseId/index'
import { Route as CoursesCourseIdMaterialsIndexRouteImport } from './routes/courses/$courseId/materials/index'
import { Route as CoursesCourseIdExamsIndexRouteImport } from './routes/courses/$courseId/exams/index'
import { Route as CoursesCourseIdExamprepIndexRouteImport } from './routes/courses/$courseId/examprep/index'
import { Route as CoursesCourseIdExamprepExamIdRouteImport } from './routes/courses/$courseId/examprep/$examId'

const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesCourseIdIndexRoute = CoursesCourseIdIndexRouteImport.update({
  id: '/courses/$courseId/',
  path: '/courses/$courseId/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesCourseIdMaterialsIndexRoute =
  CoursesCourseIdMaterialsIndexRouteImport.update({
    id: '/courses/$courseId/materials/',
    path: '/courses/$courseId/materials/',
    getParentRoute: () => rootRouteImport,
  } as any)
const CoursesCourseIdExamsIndexRoute =
  CoursesCourseIdExamsIndexRouteImport.update({
    id: '/courses/$courseId/exams/',
    path: '/courses/$courseId/exams/',
    getParentRoute: () => rootRouteImport,
  } as any)
const CoursesCourseIdExamprepIndexRoute =
  CoursesCourseIdExamprepIndexRouteImport.update({
    id: '/courses/$courseId/examprep/',
    path: '/courses/$courseId/examprep/',
    getParentRoute: () => rootRouteImport,
  } as any)
const CoursesCourseIdExamprepExamIdRoute =
  CoursesCourseIdExamprepExamIdRouteImport.update({
    id: '/courses/$courseId/examprep/$examId',
    path: '/courses/$courseId/examprep/$examId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/courses/': typeof CoursesIndexRoute
  '/courses/$courseId/': typeof CoursesCourseIdIndexRoute
  '/courses/$courseId/examprep/$examId': typeof CoursesCourseIdExamprepExamIdRoute
  '/courses/$courseId/examprep/': typeof CoursesCourseIdExamprepIndexRoute
  '/courses/$courseId/exams/': typeof CoursesCourseIdExamsIndexRoute
  '/courses/$courseId/materials/': typeof CoursesCourseIdMaterialsIndexRoute
}
export interface FileRoutesByTo {
  '/courses': typeof CoursesIndexRoute
  '/courses/$courseId': typeof CoursesCourseIdIndexRoute
  '/courses/$courseId/examprep/$examId': typeof CoursesCourseIdExamprepExamIdRoute
  '/courses/$courseId/examprep': typeof CoursesCourseIdExamprepIndexRoute
  '/courses/$courseId/exams': typeof CoursesCourseIdExamsIndexRoute
  '/courses/$courseId/materials': typeof CoursesCourseIdMaterialsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/courses/': typeof CoursesIndexRoute
  '/courses/$courseId/': typeof CoursesCourseIdIndexRoute
  '/courses/$courseId/examprep/$examId': typeof CoursesCourseIdExamprepExamIdRoute
  '/courses/$courseId/examprep/': typeof CoursesCourseIdExamprepIndexRoute
  '/courses/$courseId/exams/': typeof CoursesCourseIdExamsIndexRoute
  '/courses/$courseId/materials/': typeof CoursesCourseIdMaterialsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/courses/'
    | '/courses/$courseId/'
    | '/courses/$courseId/examprep/$examId'
    | '/courses/$courseId/examprep/'
    | '/courses/$courseId/exams/'
    | '/courses/$courseId/materials/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/courses'
    | '/courses/$courseId'
    | '/courses/$courseId/examprep/$examId'
    | '/courses/$courseId/examprep'
    | '/courses/$courseId/exams'
    | '/courses/$courseId/materials'
  id:
    | '__root__'
    | '/courses/'
    | '/courses/$courseId/'
    | '/courses/$courseId/examprep/$examId'
    | '/courses/$courseId/examprep/'
    | '/courses/$courseId/exams/'
    | '/courses/$courseId/materials/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  CoursesIndexRoute: typeof CoursesIndexRoute
  CoursesCourseIdIndexRoute: typeof CoursesCourseIdIndexRoute
  CoursesCourseIdExamprepExamIdRoute: typeof CoursesCourseIdExamprepExamIdRoute
  CoursesCourseIdExamprepIndexRoute: typeof CoursesCourseIdExamprepIndexRoute
  CoursesCourseIdExamsIndexRoute: typeof CoursesCourseIdExamsIndexRoute
  CoursesCourseIdMaterialsIndexRoute: typeof CoursesCourseIdMaterialsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/courses/': {
      id: '/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$courseId/': {
      id: '/courses/$courseId/'
      path: '/courses/$courseId'
      fullPath: '/courses/$courseId/'
      preLoaderRoute: typeof CoursesCourseIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$courseId/materials/': {
      id: '/courses/$courseId/materials/'
      path: '/courses/$courseId/materials'
      fullPath: '/courses/$courseId/materials/'
      preLoaderRoute: typeof CoursesCourseIdMaterialsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$courseId/exams/': {
      id: '/courses/$courseId/exams/'
      path: '/courses/$courseId/exams'
      fullPath: '/courses/$courseId/exams/'
      preLoaderRoute: typeof CoursesCourseIdExamsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$courseId/examprep/': {
      id: '/courses/$courseId/examprep/'
      path: '/courses/$courseId/examprep'
      fullPath: '/courses/$courseId/examprep/'
      preLoaderRoute: typeof CoursesCourseIdExamprepIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$courseId/examprep/$examId': {
      id: '/courses/$courseId/examprep/$examId'
      path: '/courses/$courseId/examprep/$examId'
      fullPath: '/courses/$courseId/examprep/$examId'
      preLoaderRoute: typeof CoursesCourseIdExamprepExamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  CoursesIndexRoute: CoursesIndexRoute,
  CoursesCourseIdIndexRoute: CoursesCourseIdIndexRoute,
  CoursesCourseIdExamprepExamIdRoute: CoursesCourseIdExamprepExamIdRoute,
  CoursesCourseIdExamprepIndexRoute: CoursesCourseIdExamprepIndexRoute,
  CoursesCourseIdExamsIndexRoute: CoursesCourseIdExamsIndexRoute,
  CoursesCourseIdMaterialsIndexRoute: CoursesCourseIdMaterialsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
